In [ ]:
!pip3 install pandas
!pip3 install openpyxl # Required for writing to Excel files

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in /Users/phuocpham/Library/Python/3.9/lib/python/site-packages (2.3.3)
Requirement already satisfied: pytz>=2020.1 in /Users/phuocpham/Library/Python/3.9/lib/python/site-packages (from pandas) (2026.1.post1)
Requirement already satisfied: tzdata>=2022.7 in /Users/phuocpham/Library/Python/3.9/lib/python/site-packages (from pandas) (2026.1)
Requirement already satisfied: numpy>=1.22.4 in /Users/phuocpham/Library/Python/3.9/lib/python/site-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/phuocpham/Library/Python/3.9/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas) (1.15.0)
WARNING: You are using pip version 21.2.4; however, version 26.0.1 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: openpyxl in /Users/phuocpham/Library/Python/3.9/lib/python/site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /Users/phuocpham/Library/Python/3.9/lib/python/site-packages (from openpyxl) (2.0.0)
WARNING: You are using pip version 21.2.4; however, version 26.0.1 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.

In [10]:
from pandas import DataFrame

l1 = [1,2,3,4]
l2 = [1,2,3,4]
df = DataFrame({'Stimulus Time': l1, 'Reaction Time': l2})
df

   Stimulus Time  Reaction Time
0              1              1
1              2              2
2              3              3
3              4              4

In [16]:
df.to_excel('test.xlsx', sheet_name='sheet1', index=False)
df.to_csv('test.csv', index=False)

In [19]:
# Construct DataFrame from a list of dictionaries

data = [{'Stimulus Time': 1, 'Reaction Time': 1},
        {'Stimulus Time': 2, 'Reaction Time': 2},
        {'Stimulus Time': 3, 'Reaction Time': 3},
        {'Stimulus Time': 4, 'Reaction Time': 4}]
df = DataFrame(data)
df

   Stimulus Time  Reaction Time
0              1              1
1              2              2
2              3              3
3              4              4

In [20]:
df.to_csv('test_from_dict.csv', index=False)